src/ServiceBundle/Form/Administration/AlertType.php
<?php

namespace ServiceBundle\Form\Administration;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use ServiceBundle\Entity\Administration\Alert;
use ServiceBundle\Entity\UserManagment\User;

use ServiceBundle\FormType\AlertType as AlertTypeField;

class AlertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class, array('label' => 'alert.field.title'))
                ->add('description', TextType::class, array('label' => 'alert.field.description'))
                ->add('type', AlertTypeField::class, array('label' => 'alert.field.type'))
                ->add('users', EntityType::class, array(
                    'class' => User::class,
                    'label' => false,
                    'multiple' => true,
                    // use the User.username property as the visible option string
                    'choice_label' => 'username',
                    'attr' => [ 'placeholder' => 'alert.field.user']
                    )
                )
                ->add('submit', SubmitType::class ,array(
                    'attr' => ['button_type' => 'round'],
                    'label' => 'alert.field.submit'
                ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Alert::class
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicebundle_administration_alert';
    }


}

src/ServiceBundle/Form/Administration/ContactUSType.php
<?php

namespace ServiceBundle\Form\Administration;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

use ServiceBundle\Entity\Administration\ContactUS;

class ContactUSType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, array('label' => 'contactus.field.name'))
                ->add('email', TextType::class, array('label' => 'contactus.field.email'))
                ->add('message', TextareaType::class, array('label' => 'contactus.field.message'))
                ->add('save', SubmitType::class, array(
                    'attr' => ['button_type' => 'round'],
                    'label' => 'contactus.field.submit'
                ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => ContactUS::class
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicebundle_administration_contactus';
    }


}

src/ServiceBundle/Form/BusinessDirectory/BusinessDirectoryType.php
<?php

namespace ServiceBundle\Form\BusinessDirectory;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use ServiceBundle\FormType\SectorType;

use ServiceBundle\Entity\BusinessDirectory\Sector;
use ServiceBundle\Entity\BusinessDirectory\BusinessDirectory;

class BusinessDirectoryType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('companyName', TextType::class, array('label' => 'business_directory.field.company_name'))
            ->add('sector', SectorType::class, array(
                'label' => false,
                'attr' => [ 'placeholder' => 'business_directory.field.sector']
                )
            )
            ->add('companyAddress', TextType::class, array(
              'label' => 'business_directory.field.company_address',
              'attr' => ['placeholder' => ' '],
            ))
            ->add('longitude', TextType::class, array('label' => 'business_directory.field.longitude'))
            ->add('latitude', TextType::class, array('label' => 'business_directory.field.latitude'))
            ->add('save', SubmitType::class, array(
                'attr' => ['button_type' => 'square', 'class' => 'md-btn md-btn-small md-btn-flat md-btn-flat-primary'],
                'label' => 'business_directory.field.submit'
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => BusinessDirectory::class
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicebundle_businessdirectory';
    }
}

src/ServiceBundle/Form/Search/SearchType.php
<?php

namespace ServiceBundle\Form\Search;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SearchType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('search', TextType::class, ['attr' => ['placeholder' => 'search'] , 'label' => 'search.by_every_thing']);
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'service_search';
    }
}

src/ServiceBundle/Form/User/ProfileFormType.php
<?php

namespace ServiceBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\ProfileFormType as FOSProfileFormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class ProfileFormType extends AbstractType
{
    /**
     * Builds the embedded form representing the user.
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('imageFile',  VichImageType::class, array(
                    'allow_delete' => false, // not mandatory, default is true
                    'download_link' => false, // not mandatory, default is true
                    'label' => false)
                )
                ->add('firstName', TextType::class, array('label' => 'user.field.first_name'))
                ->add('lastName', TextType::class, array('label' => 'user.field.last_name'))
                ->add('birthday', DateType::class,
                  array(
                    'label' => 'user.field.birthday',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [ 'data-uk-datepicker'=> "{format:'YYYY-MM-DD'}"],
                  )
                )
                ->add('summary', TextareaType::class, array('label' => 'user.field.summary'))
                ->add('currentPosition', TextType::class, array('label' => 'user.field.current_position'))
                ->add('phone', TextType::class, array('label' => 'user.field.phone'))
                ->add('country', CountryType::class, array('label' => 'user.field.country'))
                ->add('codeZIP', TextType::class, array('label' => 'user.field.code_zip'))
                ->add('address', TextareaType::class, array('label' => 'user.field.address'))
              ;
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return FOSProfileFormType::class ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'service_user_profile';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/ServiceBundle/Form/User/RegistrationType.php
<?php

namespace ServiceBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use FOS\UserBundle\Form\Type\RegistrationFormType;
use ServiceBundle\Entity\UserManagment\User;

class RegistrationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return RegistrationFormType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
        ));
    }
}

src/ServiceBundle/Form/User/UserFormType.php
<?php

namespace ServiceBundle\Form\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\ProfileFormType as FOSProfileFormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class UserFormType extends AbstractType
{
    /**
     * Builds the embedded form representing the user.
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('imageFile',  VichImageType::class, array(
                    'allow_delete' => false, // not mandatory, default is true
                    'download_link' => false, // not mandatory, default is true
                    'label' => false)
                )
                ->add('firstName', TextType::class, array('label' => 'user.field.first_name'))
                ->add('lastName', TextType::class, array('label' => 'user.field.last_name'))
                ->add('birthday', DateType::class,
                  array(
                    'label' => 'user.field.birthday',
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => [ 'data-uk-datepicker'=> "{format:'YYYY-MM-DD'}"],
                  )
                )
                ->add('summary', TextareaType::class, array('label' => 'user.field.summary'))
                ->add('currentPosition', TextType::class, array('label' => 'user.field.current_position'))
                ->add('phone', TextType::class, array('label' => 'user.field.phone'))
                ->add('country', CountryType::class, array('label' => 'user.field.country'))
                ->add('codeZIP', TextType::class, array('label' => 'user.field.code_zip'))
                ->add('address', TextareaType::class, array('label' => 'user.field.address'))
              ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'service_user_profile';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/ServiceBundle/Form/UserCV/EducationType.php
<?php

namespace ServiceBundle\Form\UserCV;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use ServiceBundle\FormType\MonthType;
use ServiceBundle\FormType\YearType;
use ServiceBundle\FormType\HiddenEntityType;

use ServiceBundle\Entity\UserCV\Education;
use ServiceBundle\Entity\UserManagment\User as User;

class EducationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder->add('school', TextType::class, array('label' => 'education.field.school'))
                ->add('degree', TextType::class, array('label' => 'education.field.degree'))
                ->add('fieldOfStudy', TextType::class, array('label' => 'education.field.fieldOfStudy'))
                ->add('grade', TextType::class, array('label' => 'education.field.grade'))
                ->add('description', TextareaType::class, array('label' => 'education.field.description'))
                ->add('fromYear', YearType::class, array('label' => 'education.field.fromYear'))
                ->add('toYear', YearType::class, array('label' => 'education.field.toYear'))
                ->add('user', HiddenEntityType::class, array(
                      'class' => User::class,
                      'data' =>  $user,
                ))
                ->add('submit', SubmitType::class ,array(
                    'attr' => ['button_type' => 'normal'],
                    'label' => 'education.field.submit'
                ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Education::class
        ));
        $resolver->setRequired('user');
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicebundle_usercv_education';
    }


}

src/ServiceBundle/Form/UserCV/ExperienceType.php
<?php

namespace ServiceBundle\Form\UserCV;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use ServiceBundle\FormType\MonthType;
use ServiceBundle\FormType\YearType;
use ServiceBundle\FormType\HiddenEntityType;

use ServiceBundle\Entity\UserCV\Experience;
use ServiceBundle\Entity\UserManagment\User as User;

class ExperienceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder
            ->add('title', TextType::class, array('label' => 'experience.field.title'))
            ->add('company', TextType::class, array('label' => 'experience.field.company'))
            ->add('location', TextType::class, array('label' => 'experience.field.location'))
            ->add('description', TextareaType::class, array('label' => 'experience.field.description'))
            ->add('fromYear', YearType::class, array('label' => 'experience.field.fromYear'))
            ->add('fromMonth', MonthType::class, array('label' => 'experience.field.fromMonth'))
            ->add('toYear', YearType::class, array('label' => 'experience.field.toYear'))
            ->add('toMonth', MonthType::class, array('label' => 'experience.field.toMonth'))
            ->add('currentlyWorkHere', CheckboxType::class, array('label' => 'experience.field.currently_work_here'))
            ->add('user', HiddenEntityType::class, array(
                  'class' => User::class,
                  'data' =>  $user,
            ))
            ->add('submit', SubmitType::class ,array(
                'attr' => ['button_type' => 'normal'],
                'label' => 'experience.field.submit'
            ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Experience::class
        ));
        $resolver->setRequired('user');
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicebundle_experience';
    }


}

templates/form/layout.html.twig
{% block form_row %}
  {% spaceless %}
    <div class="uk-form-row input-field">
      {{ form_label(form) }}
      {{ form_widget(form) }}
      <div class="parsley-errors-list filled uk-text-danger text-danger">
        {{ form_errors(form) }}
      </div>
    </div>
  {% endspaceless %}
{% endblock form_row %}
{%- block choice_widget -%}
  {% if expanded %}
    {{- block('choice_widget_expanded') -}}
  {% else %}
    {{- block('choice_widget_collapsed') -}}
  {% endif %}
{%- endblock choice_widget -%}

{% block button_row -%}
  {{- form_widget(form) -}}
{%- endblock button_row %}

{%- block button_widget -%}
  {% if attr.button_type is defined and attr.button_type == 'round' %}
    <div class="uk-form-row">
      <div class="md-fab-wrapper {{ attr.round_type|default('md-fab-in-card') }}">
        <button type="{{ type|default('button') }}" title="{{ 'action.save'|trans }}" class="md-fab md-fab-accent md-fab-wave waves-effect waves-button" data-uk-tooltip="{pos:'top'}" {{ block('button_attributes') }}>
          <i class="material-icons">&#xE161;</i>
        </button>
      </div>
    </div>
  {% else %}
    {% set attr = attr|merge({'class': attr.class|default('md-btn save md-btn-primary md-btn-wave-light md-btn-icon')|trim }) %}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>
       {{ label|trans }}
    </button>
  {% endif %}
{%- endblock button_widget -%}

{%- block choice_widget_collapsed -%}
  {%- if required and placeholder is none and not placeholder_in_choices and not multiple and (attr.size is not defined or attr.size <= 1) -%}
    {% set required = false %}
  {%- endif -%}
  <select {% if attr.selectize is not defined %} data-md-selectize {% endif %} data-md-selectize  {{ block('widget_attributes') }} {% if multiple %} multiple="multiple" {% endif %}>
    {%- if placeholder is not none -%}
      <option value="" {% if required and value is empty %} selected="selected" {% endif %}>{{ placeholder != '' ? (translation_domain is same as(false) ? placeholder : placeholder|trans({}, translation_domain)) }}</option>
    {%- endif -%}
    {%- if preferred_choices|length > 0 -%}
      {% set options = preferred_choices %}
      {{- block('choice_widget_options') -}}
      {%- if choices|length > 0 and separator is not none -%}
        <option disabled="disabled">{{ separator }}</option>
      {%- endif -%}
    {%- endif -%}
    {%- set options = choices -%}
    {{- block('choice_widget_options') -}}
  </select>
{%- endblock choice_widget_collapsed -%}

{%- block form_widget -%}
  {% if compound %}
    {{- block('form_widget_compound') -}}
  {% else %}
    {{- block('form_widget_simple') -}}
  {% endif %}
{%- endblock form_widget -%}

{%- block form_widget_simple -%}
  {%- set type = type|default('text') -%}
  {% if type == "file" %}
    {% if download_uri is defined and download_uri %}
      {% set value = download_uri %}
    {% endif %}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %} {% endif %}/>
  {% else %}
    {% set attr = attr|merge({'class': (attr.class|default(' md-input'))|trim }) %}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %} value="{{ value }}" {% endif %}/>
  {% endif %}
{%- endblock form_widget_simple -%}

{%- block form_widget_compound -%}
  {%- if form.parent is empty -%}
    {{ form_errors(form) }}
  {%- endif -%}
  {{- block('form_rows') -}}
  {{- form_rest(form) -}}
{%- endblock form_widget_compound -%}

{%- block textarea_widget -%}
  <textarea class="md-input materialize-textarea" {{ block('widget_attributes') }}>{{ value }}</textarea>
{%- endblock textarea_widget -%}

{% block form_errors %}
  {% spaceless %}
    {% if errors | length > 0 %}
      {% if compound %}
        <div class="uk-alert uk-alert-danger" data-uk-alert="">
          <a href="#" class="uk-alert-close uk-close"></a>
          {% for error in errors %}
            <p>{{ error.message }}</p>
          {% endfor %}
        </div>
      {% else %}
        {% for error in errors %}
          <span class="parsley-required">
            {{ error.message }}</span>
        {% endfor %}
      {% endif %}
    {% endif %}
  {% endspaceless %}
{% endblock form_errors %}

{%- block checkbox_widget -%}
  <input type="checkbox" {{ block('widget_attributes') }} {% if value is defined %} value="{{ value }}" {% endif %} {% if checked %} checked="checked" {% endif %}/>
{%- endblock checkbox_widget -%}

{%- block form -%}
  {{ form_start(form) }}
  {{- form_widget(form) -}}
  {{ form_end(form) }}
{%- endblock form -%}

{%- block form_start -%}
  {% set method = method | upper %}
  {%- if method in ["GET", "POST"] -%}
    {% set form_method = method %}
  {%- else -%}
    {% set form_method = "POST" %}
  {%- endif -%}
  <form
    novalidate="novalidate"
    class="uk-form-stacked"
    name="{{ name }}"
    method="{{ form_method|lower }}"
    {% if action != '' %}
    action="{{ action }}"
    {% endif %}
    {% for attrname, attrvalue in attr %}
    {{ attrname }}="{{ attrvalue }}"
    {% endfor %}
    {% if multipart %}
    enctype="multipart/form-data"
    {% endif %}>
    {%- if form_method != method -%}
      <input type="hidden" name="_method" value="{{ method }}"/>
    {%- endif -%}
  {%- endblock form_start -%}

  {%- block form_label -%}
    {% if label is not same as(false) -%}
      {% if not compound -%}
        {% set label_attr = label_attr|merge({'for': id}) %}
      {%- endif -%}
      {% if required -%}
        {% set label_attr = label_attr|merge({
          'class': (label_attr.class|default('') ~ ' required') | trim
        }) %}
      {%- endif -%}
      {% if label is empty -%}
        {%- if label_format is not empty -%}
          {% set label = label_format|replace({'%name%': name, '%id%': id}) %}
        {%- else -%}
          {% set label = name|humanize %}
        {%- endif -%}
      {%- endif -%}
      <label {% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}" {% endfor %}>
        {{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</label>
    {%- endif -%}
  {%- endblock form_label -%}

  {% block vich_file_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
  {%- endblock %}

  {% block vich_file_widget %}
    {% spaceless %}
      <div class="vich-file">
        {{ form_widget(form.file) }}
        {% if form.delete is defined %}
          {{ form_row(form.delete) }}
        {% endif %}

        {% if download_uri is defined and download_uri %}
          <a href="{{ download_uri }}">{{ 'download'|trans({}, 'VichUploaderBundle') }}</a>
        {% endif %}
      </div>
    {% endspaceless %}
  {% endblock %}

  {% block vich_image_row -%}
    {% set force_error = true %}
    {{- block('form_row') }}
  {%- endblock %}

  {% block vich_image_widget %}
    {% spaceless %}
      {{ form_widget(form.file , {"attr" :  {'class' : "dropify" }}) }}
      {% if form.delete is defined %}
        {{ form_row(form.delete) }}
      {% endif %}

      {% if show_download_link and download_uri is defined and download_uri %}
        <a href="{{ download_uri }}">{{ 'download'|trans({}, 'VichUploaderBundle') }}</a>
      {% endif %}

    {% endspaceless %}
  {% endblock %}
  {% block sms_translatable_field_widget %}
    {{ form_errors(form) }}
    <div class="sms_translations tabbable">
      <ul class="uk-tab" data-uk-tab="{connect:'#{{ form.vars.field }}'}">
        {% for translationsFields in form.vars.locales %}
          {% set locale = translationsFields %}

          <li class="{% if app.request.locale == locale %}uk-active{% endif %}">
            <a href="#" data-toggle="tab">
              {{ locale|capitalize }}
              {% if locale == form.vars.default_locale %}[*]{% endif %}
            </a>
          </li>
        {% endfor %}
      </ul>

      <ul id="{{ form.vars.field }}" class="uk-switcher uk-margin">
        {% for translationsFields in form %}
          {% set locale = translationsFields.vars.name %}

          <li class="uk-margin-small-top {% if app.request.locale == locale %}uk-active{% endif %}">
            {{ form_label(form) }}
            {{ form_widget(translationsFields) }}
            {{ form_errors(translationsFields) }}
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endblock %}